<?php
/**
 * @file
 * Code for the 4Prima Organization feature.
 */

include_once 'prima_organization.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function prima_organization_ctools_plugin_directory($module, $plugin) {
  if ($module == 'addressfield') {
    return 'plugins/' . $plugin;
  }
}

function user_has_roles($roles) {
  //checks if user has role/roles
  return !!count(array_intersect(is_array($roles)? $roles : array($roles), array_values($GLOBALS['user']->roles)));
}

/**
 * Implements hook_node_presave().
 */
function prima_organization_node_presave($node) {
  if (user_is_anonymous() || (user_is_logged_in() && !user_has_roles('administrator'))) {
    $node->status = FALSE;
  }
}

function prima_organization_form_alter(&$form, &$form_state,$form_id) {
  switch($form_id){
   case 'organization_node_form':
   case 'registration_form':
     if (user_is_anonymous()) {
       $form['captcha'] = array(
         '#type' => 'captcha',
         '#captcha_type' => 'default',
         '#weight' => 99,
       );
       $form['actions']['#weight'] = 999;
     }
     break;
 }
/* echo '<pre>';
  print_r($form);
 echo '<pre>';*/

 return $form;
}
